parameters:
    ezplatform.ee.installer.class: EzSystems\EzPlatformEnterpriseEditionInstallerBundle\Installer\Installer

services:
    ezstudio.installer.studio_installer:
        class: %ezplatform.ee.installer.class%
        parent: ezplatform.installer.clean_installer
        tags:
            - {name: ezplatform.installer, type: ezplatform-ee-clean}

    EzSystems\EzPlatformEnterpriseEditionInstallerBundle\Event\Subscriber\BuildSchemaSubscriber:
        autoconfigure: true
        public: false
        arguments:
            - '@=service("kernel").locateResource("@EzPlatformEnterpriseEditionInstallerBundle/Resources/config/storage/schema.yaml")'
